// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"hash/fnv"
)

// Hash computes a hash value for MailAnalyticsListenerBreakdownItem using FNV-1a.
// Equal objects must produce equal hashes.
func (a MailAnalyticsListenerBreakdownItem) Hash() uint64 {
	h := fnv.New64a()

	// Hash primitive field: ListenerID
	h.Write([]byte(fmt.Sprintf("%v", a.ListenerID)))
	// Hash primitive field: DisplayName
	h.Write([]byte(fmt.Sprintf("%v", a.DisplayName)))
	// Hash primitive field: ListenerState
	h.Write([]byte(fmt.Sprintf("%v", a.ListenerState)))
	// Hash primitive field: EgressTasks
	h.Write([]byte(fmt.Sprintf("%v", a.EgressTasks)))
	return h.Sum64()
}
