// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides BearerAuth security value.
	// Bearer access token verified through the control plane's existing ZITADEL authentication and
	// principal-normalization flow. Operation authorization and tenant ownership are enforced separately
	// from generated validation.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	AddRecipientSetMemberOperation:                              []string{},
	BatchAddRecipientSetMembersOperation:                        []string{},
	BatchDeleteRecipientSetMembersOperation:                     []string{},
	ClaimTenantIdentityAccessOperation:                          []string{},
	CreateAPIKeyOperation:                                       []string{},
	CreateAutoReplyTemplateOperation:                            []string{},
	CreateDomainOperation:                                       []string{},
	CreateInboundRouteOperation:                                 []string{},
	CreateListenerOperation:                                     []string{},
	CreateRecipientSetOperation:                                 []string{},
	CreateRoutingRuleOperation:                                  []string{},
	CreateSMTPForwardDestinationOperation:                       []string{},
	CreateSMTPRelayOperation:                                    []string{},
	CreateStorageIntegrationOperation:                           []string{},
	CreateTenantAppleIdentityProviderOperation:                  []string{},
	CreateTenantAzureADIdentityProviderOperation:                []string{},
	CreateTenantGitHubEnterpriseServerIdentityProviderOperation: []string{},
	CreateTenantGitHubIdentityProviderOperation:                 []string{},
	CreateTenantGitLabIdentityProviderOperation:                 []string{},
	CreateTenantGitLabSelfHostedIdentityProviderOperation:       []string{},
	CreateTenantGoogleIdentityProviderOperation:                 []string{},
	CreateTenantIdentityProviderOperation:                       []string{},
	CreateTenantJWTIdentityProviderOperation:                    []string{},
	CreateTenantLDAPIdentityProviderOperation:                   []string{},
	CreateTenantOAuthIdentityProviderOperation:                  []string{},
	CreateTenantSAMLIdentityProviderOperation:                   []string{},
	CreateTenantSuppressionOperation:                            []string{},
	CreateWebhookEndpointOperation:                              []string{},
	DeleteAPIKeyOperation:                                       []string{},
	DeleteAutoReplyTemplateOperation:                            []string{},
	DeleteDomainOperation:                                       []string{},
	DeleteInboundRouteOperation:                                 []string{},
	DeleteListenerOperation:                                     []string{},
	DeleteListenerMTARateLimitOverrideOperation:                 []string{},
	DeleteRecipientSetOperation:                                 []string{},
	DeleteRecipientSetMemberOperation:                           []string{},
	DeleteRoutingRuleOperation:                                  []string{},
	DeleteSMTPForwardDestinationOperation:                       []string{},
	DeleteSMTPRelayOperation:                                    []string{},
	DeleteStorageIntegrationOperation:                           []string{},
	DeleteTenantIdentityProviderOperation:                       []string{},
	DeleteTenantMTARateLimitOverrideOperation:                   []string{},
	DeleteTenantSuppressionOperation:                            []string{},
	DeleteWebhookEndpointOperation:                              []string{},
	GetAutoReplyTemplateOperation:                               []string{},
	GetAutoReplyTemplateByRefOperation:                          []string{},
	GetDomainOperation:                                          []string{},
	GetInboundRouteOperation:                                    []string{},
	GetListenerOperation:                                        []string{},
	GetListenerMTARateLimitOverrideOperation:                    []string{},
	GetMailAnalyticsActivityHeatmapOperation:                    []string{},
	GetMailAnalyticsBreakdownOperation:                          []string{},
	GetMailAnalyticsComparisonOperation:                         []string{},
	GetMailAnalyticsDomainLifecycleOperation:                    []string{},
	GetMailAnalyticsLifecycleOperation:                          []string{},
	GetMailAnalyticsOverviewOperation:                           []string{},
	GetMailAnalyticsSeriesOperation:                             []string{},
	GetMailAnalyticsTaskSizeStatisticsOperation:                 []string{},
	GetRecipientSetOperation:                                    []string{},
	GetRoutingRuleOperation:                                     []string{},
	GetSMTPForwardDestinationOperation:                          []string{},
	GetSMTPForwardDestinationByRefOperation:                     []string{},
	GetSMTPRelayOperation:                                       []string{},
	GetSMTPRelayByRefOperation:                                  []string{},
	GetSendingDomainPolicyOperation:                             []string{},
	GetStorageIntegrationOperation:                              []string{},
	GetStorageIntegrationByRefOperation:                         []string{},
	GetTenantOperation:                                          []string{},
	GetTenantIdentityProviderOperation:                          []string{},
	GetTenantIdentityProvisioningOperation:                      []string{},
	GetTenantMTARateLimitOverrideOperation:                      []string{},
	GetTenantOutboundPauseOperation:                             []string{},
	GetTenantQuotasOperation:                                    []string{},
	GetTenantReputationOperation:                                []string{},
	GetTenantSuppressionOperation:                               []string{},
	GetWebhookEndpointOperation:                                 []string{},
	GetWebhookEndpointByRefOperation:                            []string{},
	ListAPIKeysOperation:                                        []string{},
	ListAuditLogOperation:                                       []string{},
	ListAutoReplyTemplatesOperation:                             []string{},
	ListDomainListenerGrantsOperation:                           []string{},
	ListDomainsOperation:                                        []string{},
	ListInboundRoutesOperation:                                  []string{},
	ListInboundRoutingOutcomesOperation:                         []string{},
	ListListenersOperation:                                      []string{},
	ListRecipientSetMembersOperation:                            []string{},
	ListRecipientSetsOperation:                                  []string{},
	ListRoutingRulesOperation:                                   []string{},
	ListSMTPForwardDestinationsOperation:                        []string{},
	ListSMTPRelaysOperation:                                     []string{},
	ListStorageIntegrationsOperation:                            []string{},
	ListTenantDedicatedIPPoolsOperation:                         []string{},
	ListTenantDeliverabilityFindingsOperation:                   []string{},
	ListTenantIdentityProvidersOperation:                        []string{},
	ListTenantSuppressionsOperation:                             []string{},
	ListWebhookEndpointDeliveriesOperation:                      []string{},
	ListWebhookEndpointsOperation:                               []string{},
	PutListenerMTARateLimitOverrideOperation:                    []string{},
	PutTenantMTARateLimitOverrideOperation:                      []string{},
	ReorderRoutingRuleOperation:                                 []string{},
	ReplaceDomainOperation:                                      []string{},
	ReplaceRoutingRuleOperation:                                 []string{},
	ReplaceSendingDomainPolicyOperation:                         []string{},
	RotateWebhookEndpointSecretOperation:                        []string{},
	SearchTenantResourcesOperation:                              []string{},
	SendSMTPForwardDestinationVerificationOperation:             []string{},
	SetAutoReplyTemplateActiveOperation:                         []string{},
	SetRoutingRuleActiveOperation:                               []string{},
	SetSMTPRelayActiveOperation:                                 []string{},
	SetStorageIntegrationActiveOperation:                        []string{},
	SetTenantIdentityProviderAutoGrantOperation:                 []string{},
	SetWebhookEndpointActiveOperation:                           []string{},
	UpdateAutoReplyTemplateOperation:                            []string{},
	UpdateInboundRouteOperation:                                 []string{},
	UpdateListenerOperation:                                     []string{},
	UpdateListenerDefaultTerminalActionOperation:                []string{},
	UpdateListenerRspamdScanningOperation:                       []string{},
	UpdateRecipientSetOperation:                                 []string{},
	UpdateSMTPRelayOperation:                                    []string{},
	UpdateStorageIntegrationOperation:                           []string{},
	UpdateTenantIdentityProvisioningOperation:                   []string{},
	UpdateTenantSuppressionOperation:                            []string{},
	UpdateWebhookEndpointOperation:                              []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
