// Code generated by ogen, DO NOT EDIT.

package api

import "github.com/ogen-go/ogen/validate"

// Equal compares two MailAnalyticsListenerBreakdownItem instances for equality.
// The depth parameter prevents infinite recursion on nested objects.
func (a MailAnalyticsListenerBreakdownItem) Equal(b MailAnalyticsListenerBreakdownItem, depth int) bool {
	if depth > 10 {
		panic(&validate.DepthLimitError{
			MaxDepth: 10,
			TypeName: "MailAnalyticsListenerBreakdownItem",
		})
	}

	if a.ListenerID != b.ListenerID {
		return false
	}
	if a.DisplayName != b.DisplayName {
		return false
	}
	if a.ListenerState != b.ListenerState {
		return false
	}
	if a.EgressTasks != b.EgressTasks {
		return false
	}
	return true
}
