// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *CreateInboundRouteRequest) setDefaults() {
	{
		val := bool(false)
		s.OnboardDomainIfMissing.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateTenantIdentityProviderRequest) setDefaults() {
	{
		val := CreateTenantIdentityProviderRequestProviderType("oidc")
		s.ProviderType.SetTo(val)
	}
}
