// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/google/uuid"
)

// AddRecipientSetMemberParams is parameters of addRecipientSetMember operation.
type AddRecipientSetMemberParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// BatchAddRecipientSetMembersParams is parameters of batchAddRecipientSetMembers operation.
type BatchAddRecipientSetMembersParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// BatchDeleteRecipientSetMembersParams is parameters of batchDeleteRecipientSetMembers operation.
type BatchDeleteRecipientSetMembersParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// ClaimTenantIdentityAccessParams is parameters of claimTenantIdentityAccess operation.
type ClaimTenantIdentityAccessParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateAPIKeyParams is parameters of createAPIKey operation.
type CreateAPIKeyParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// CreateAutoReplyTemplateParams is parameters of createAutoReplyTemplate operation.
type CreateAutoReplyTemplateParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateDomainParams is parameters of createDomain operation.
type CreateDomainParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateInboundRouteParams is parameters of createInboundRoute operation.
type CreateInboundRouteParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateListenerParams is parameters of createListener operation.
type CreateListenerParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateRecipientSetParams is parameters of createRecipientSet operation.
type CreateRecipientSetParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateRoutingRuleParams is parameters of createRoutingRule operation.
type CreateRoutingRuleParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// CreateSMTPForwardDestinationParams is parameters of createSMTPForwardDestination operation.
type CreateSMTPForwardDestinationParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateSMTPRelayParams is parameters of createSMTPRelay operation.
type CreateSMTPRelayParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateStorageIntegrationParams is parameters of createStorageIntegration operation.
type CreateStorageIntegrationParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantAppleIdentityProviderParams is parameters of createTenantAppleIdentityProvider operation.
type CreateTenantAppleIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantAzureADIdentityProviderParams is parameters of createTenantAzureADIdentityProvider operation.
type CreateTenantAzureADIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantGitHubEnterpriseServerIdentityProviderParams is parameters of createTenantGitHubEnterpriseServerIdentityProvider operation.
type CreateTenantGitHubEnterpriseServerIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantGitHubIdentityProviderParams is parameters of createTenantGitHubIdentityProvider operation.
type CreateTenantGitHubIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantGitLabIdentityProviderParams is parameters of createTenantGitLabIdentityProvider operation.
type CreateTenantGitLabIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantGitLabSelfHostedIdentityProviderParams is parameters of createTenantGitLabSelfHostedIdentityProvider operation.
type CreateTenantGitLabSelfHostedIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantGoogleIdentityProviderParams is parameters of createTenantGoogleIdentityProvider operation.
type CreateTenantGoogleIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantIdentityProviderParams is parameters of createTenantIdentityProvider operation.
type CreateTenantIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantJWTIdentityProviderParams is parameters of createTenantJWTIdentityProvider operation.
type CreateTenantJWTIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantLDAPIdentityProviderParams is parameters of createTenantLDAPIdentityProvider operation.
type CreateTenantLDAPIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantOAuthIdentityProviderParams is parameters of createTenantOAuthIdentityProvider operation.
type CreateTenantOAuthIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantSAMLIdentityProviderParams is parameters of createTenantSAMLIdentityProvider operation.
type CreateTenantSAMLIdentityProviderParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateTenantSuppressionParams is parameters of createTenantSuppression operation.
type CreateTenantSuppressionParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// CreateWebhookEndpointParams is parameters of createWebhookEndpoint operation.
type CreateWebhookEndpointParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// DeleteAPIKeyParams is parameters of deleteAPIKey operation.
type DeleteAPIKeyParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	// API key identifier.
	APIKeyID uuid.UUID
}

// DeleteAutoReplyTemplateParams is parameters of deleteAutoReplyTemplate operation.
type DeleteAutoReplyTemplateParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Auto-reply template identifier.
	TemplateID uuid.UUID
}

// DeleteDomainParams is parameters of deleteDomain operation.
type DeleteDomainParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Tenant domain identifier.
	DomainID uuid.UUID
}

// DeleteInboundRouteParams is parameters of deleteInboundRoute operation.
type DeleteInboundRouteParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Inbound route identifier.
	RouteID uuid.UUID
}

// DeleteListenerParams is parameters of deleteListener operation.
type DeleteListenerParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// DeleteListenerMTARateLimitOverrideParams is parameters of deleteListenerMTARateLimitOverride operation.
type DeleteListenerMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// DeleteRecipientSetParams is parameters of deleteRecipientSet operation.
type DeleteRecipientSetParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// DeleteRecipientSetMemberParams is parameters of deleteRecipientSetMember operation.
type DeleteRecipientSetMemberParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
	// Plain mailbox address without a display name.
	EmailAddress string
}

// DeleteRoutingRuleParams is parameters of deleteRoutingRule operation.
type DeleteRoutingRuleParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	RuleID     uuid.UUID
}

// DeleteSMTPForwardDestinationParams is parameters of deleteSMTPForwardDestination operation.
type DeleteSMTPForwardDestinationParams struct {
	// Tenant slug.
	Slug TenantSlug
	// SMTP forward destination identifier.
	DestinationID uuid.UUID
}

// DeleteSMTPRelayParams is parameters of deleteSMTPRelay operation.
type DeleteSMTPRelayParams struct {
	// Tenant slug.
	Slug    TenantSlug
	RelayID uuid.UUID
}

// DeleteStorageIntegrationParams is parameters of deleteStorageIntegration operation.
type DeleteStorageIntegrationParams struct {
	// Tenant slug.
	Slug          TenantSlug
	IntegrationID uuid.UUID
}

// DeleteTenantIdentityProviderParams is parameters of deleteTenantIdentityProvider operation.
type DeleteTenantIdentityProviderParams struct {
	// Tenant slug.
	Slug  TenantSlug
	IdpID uuid.UUID
}

// DeleteTenantMTARateLimitOverrideParams is parameters of deleteTenantMTARateLimitOverride operation.
type DeleteTenantMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// DeleteTenantSuppressionParams is parameters of deleteTenantSuppression operation.
type DeleteTenantSuppressionParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Plain mailbox address without a display name.
	EmailAddress string
}

// DeleteWebhookEndpointParams is parameters of deleteWebhookEndpoint operation.
type DeleteWebhookEndpointParams struct {
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}

// GetAutoReplyTemplateParams is parameters of getAutoReplyTemplate operation.
type GetAutoReplyTemplateParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Auto-reply template identifier.
	TemplateID uuid.UUID
}

// GetAutoReplyTemplateByRefParams is parameters of getAutoReplyTemplateByRef operation.
type GetAutoReplyTemplateByRefParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped auto-reply template reference.
	TemplateRef string
}

// GetDomainParams is parameters of getDomain operation.
type GetDomainParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Tenant domain identifier.
	DomainID uuid.UUID
}

// GetInboundRouteParams is parameters of getInboundRoute operation.
type GetInboundRouteParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Inbound route identifier.
	RouteID uuid.UUID
}

// GetListenerParams is parameters of getListener operation.
type GetListenerParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// GetListenerMTARateLimitOverrideParams is parameters of getListenerMTARateLimitOverride operation.
type GetListenerMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// GetMailAnalyticsActivityHeatmapParams is parameters of getMailAnalyticsActivityHeatmap operation.
type GetMailAnalyticsActivityHeatmapParams struct {
	StartAt time.Time
	EndAt   time.Time
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsBreakdownParams is parameters of getMailAnalyticsBreakdown operation.
type GetMailAnalyticsBreakdownParams struct {
	StartAt   time.Time
	EndAt     time.Time
	Metric    MailAnalyticsBreakdownMetric
	Dimension MailAnalyticsBreakdownDimension
	Limit     OptInt32 `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsComparisonParams is parameters of getMailAnalyticsComparison operation.
type GetMailAnalyticsComparisonParams struct {
	StartAt time.Time
	EndAt   time.Time
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsDomainLifecycleParams is parameters of getMailAnalyticsDomainLifecycle operation.
type GetMailAnalyticsDomainLifecycleParams struct {
	StartAt          time.Time
	EndAt            time.Time
	ObservationEndAt time.Time
	RecipientDomain  OptString `json:",omitempty,omitzero"`
	Limit            OptInt32  `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsLifecycleParams is parameters of getMailAnalyticsLifecycle operation.
type GetMailAnalyticsLifecycleParams struct {
	// Inclusive UTC task-origin cohort start, aligned to a UTC hour or day selected by the server.
	StartAt time.Time
	// Exclusive UTC task-origin cohort end, aligned to the selected granularity.
	EndAt time.Time
	// Exclusive UTC upper bound for observed lifecycle facts; must not precede end_at.
	ObservationEndAt time.Time
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsOverviewParams is parameters of getMailAnalyticsOverview operation.
type GetMailAnalyticsOverviewParams struct {
	// Inclusive UTC start of the analytics interval.
	StartAt time.Time
	// Exclusive UTC end of the analytics interval.
	EndAt time.Time
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsSeriesParams is parameters of getMailAnalyticsSeries operation.
type GetMailAnalyticsSeriesParams struct {
	StartAt   time.Time
	EndAt     time.Time
	Metric    MailAnalyticsBreakdownMetric
	Dimension MailAnalyticsBreakdownDimension
	Limit     OptInt32 `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// GetMailAnalyticsTaskSizeStatisticsParams is parameters of getMailAnalyticsTaskSizeStatistics operation.
type GetMailAnalyticsTaskSizeStatisticsParams struct {
	StartAt time.Time
	EndAt   time.Time
	// Tenant slug.
	Slug TenantSlug
}

// GetRecipientSetParams is parameters of getRecipientSet operation.
type GetRecipientSetParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// GetRoutingRuleParams is parameters of getRoutingRule operation.
type GetRoutingRuleParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	RuleID     uuid.UUID
}

// GetSMTPForwardDestinationParams is parameters of getSMTPForwardDestination operation.
type GetSMTPForwardDestinationParams struct {
	// Tenant slug.
	Slug TenantSlug
	// SMTP forward destination identifier.
	DestinationID uuid.UUID
}

// GetSMTPForwardDestinationByRefParams is parameters of getSMTPForwardDestinationByRef operation.
type GetSMTPForwardDestinationByRefParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped SMTP forward destination reference.
	DestinationRef string
}

// GetSMTPRelayParams is parameters of getSMTPRelay operation.
type GetSMTPRelayParams struct {
	// Tenant slug.
	Slug    TenantSlug
	RelayID uuid.UUID
}

// GetSMTPRelayByRefParams is parameters of getSMTPRelayByRef operation.
type GetSMTPRelayByRefParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped SMTP relay reference.
	RelayRef string
}

// GetSendingDomainPolicyParams is parameters of getSendingDomainPolicy operation.
type GetSendingDomainPolicyParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// GetStorageIntegrationParams is parameters of getStorageIntegration operation.
type GetStorageIntegrationParams struct {
	// Tenant slug.
	Slug          TenantSlug
	IntegrationID uuid.UUID
}

// GetStorageIntegrationByRefParams is parameters of getStorageIntegrationByRef operation.
type GetStorageIntegrationByRefParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped storage integration reference.
	StorageRef string
}

// GetTenantParams is parameters of getTenant operation.
type GetTenantParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantIdentityProviderParams is parameters of getTenantIdentityProvider operation.
type GetTenantIdentityProviderParams struct {
	// Tenant slug.
	Slug  TenantSlug
	IdpID uuid.UUID
}

// GetTenantIdentityProvisioningParams is parameters of getTenantIdentityProvisioning operation.
type GetTenantIdentityProvisioningParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantMTARateLimitOverrideParams is parameters of getTenantMTARateLimitOverride operation.
type GetTenantMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantOutboundPauseParams is parameters of getTenantOutboundPause operation.
type GetTenantOutboundPauseParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantQuotasParams is parameters of getTenantQuotas operation.
type GetTenantQuotasParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantReputationParams is parameters of getTenantReputation operation.
type GetTenantReputationParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// GetTenantSuppressionParams is parameters of getTenantSuppression operation.
type GetTenantSuppressionParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Plain mailbox address without a display name.
	EmailAddress string
}

// GetWebhookEndpointParams is parameters of getWebhookEndpoint operation.
type GetWebhookEndpointParams struct {
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}

// GetWebhookEndpointByRefParams is parameters of getWebhookEndpointByRef operation.
type GetWebhookEndpointByRefParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped webhook endpoint reference.
	WebhookRef string
}

// ListAPIKeysParams is parameters of listAPIKeys operation.
type ListAPIKeysParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// ListAuditLogParams is parameters of listAuditLog operation.
type ListAuditLogParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q            OptString                `json:",omitempty,omitzero"`
	ActorKind    OptListAuditLogActorKind `json:",omitempty,omitzero"`
	ActorID      OptString                `json:",omitempty,omitzero"`
	Action       OptString                `json:",omitempty,omitzero"`
	ResourceType OptString                `json:",omitempty,omitzero"`
	Status       OptListAuditLogStatus    `json:",omitempty,omitzero"`
	CreatedFrom  OptDateTime              `json:",omitempty,omitzero"`
	CreatedTo    OptDateTime              `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListAutoReplyTemplatesParams is parameters of listAutoReplyTemplates operation.
type ListAutoReplyTemplatesParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListDomainListenerGrantsParams is parameters of listDomainListenerGrants operation.
type ListDomainListenerGrantsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
	// Tenant domain identifier.
	DomainID uuid.UUID
}

// ListDomainsParams is parameters of listDomains operation.
type ListDomainsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q             OptString       `json:",omitempty,omitzero"`
	Status        OptDomainStatus `json:",omitempty,omitzero"`
	SpfVerified   OptBool         `json:",omitempty,omitzero"`
	DkimVerified  OptBool         `json:",omitempty,omitzero"`
	DmarcVerified OptBool         `json:",omitempty,omitzero"`
	// Filter domains by whether outbound sending setup is enabled.
	SendingEnabled OptBool `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListInboundRoutesParams is parameters of listInboundRoutes operation.
type ListInboundRoutesParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q OptString `json:",omitempty,omitzero"`
	// Filter by tenant-owned MTA listener identifier.
	MtaListenerID OptUUID `json:",omitempty,omitzero"`
	// Filter by exact normalized recipient domain.
	DomainName OptString `json:",omitempty,omitzero"`
	// Filter by verification state.
	IsVerified OptBool `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListInboundRoutingOutcomesParams is parameters of listInboundRoutingOutcomes operation.
type ListInboundRoutingOutcomesParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken  OptString `json:",omitempty,omitzero"`
	ListenerID OptUUID   `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListListenersParams is parameters of listListeners operation.
type ListListenersParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q OptString `json:",omitempty,omitzero"`
	// Filter by listener direction.
	ListenerType OptListenerType `json:",omitempty,omitzero"`
	// Filter by traffic class.
	StreamType OptListenerStreamType `json:",omitempty,omitzero"`
	// Filter by fallback terminal action.
	DefaultTerminalActionType OptDefaultTerminalActionType `json:",omitempty,omitzero"`
	// Filter by inbound Rspamd scanning state.
	RspamdScanningEnabled OptBool `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListRecipientSetMembersParams is parameters of listRecipientSetMembers operation.
type ListRecipientSetMembersParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q OptString `json:",omitempty,omitzero"`
	// Include members added at or after this timestamp.
	AddedFrom OptDateTime `json:",omitempty,omitzero"`
	// Include members added before this timestamp.
	AddedTo OptDateTime `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// ListRecipientSetsParams is parameters of listRecipientSets operation.
type ListRecipientSetsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListRoutingRulesParams is parameters of listRoutingRules operation.
type ListRoutingRulesParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken  OptString                `json:",omitempty,omitzero"`
	Q          OptString                `json:",omitempty,omitzero"`
	ActionType OptRoutingRuleActionKind `json:",omitempty,omitzero"`
	IsActive   OptBool                  `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// ListSMTPForwardDestinationsParams is parameters of listSMTPForwardDestinations operation.
type ListSMTPForwardDestinationsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListSMTPRelaysParams is parameters of listSMTPRelays operation.
type ListSMTPRelaysParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListStorageIntegrationsParams is parameters of listStorageIntegrations operation.
type ListStorageIntegrationsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListTenantDedicatedIPPoolsParams is parameters of listTenantDedicatedIPPools operation.
type ListTenantDedicatedIPPoolsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListTenantDeliverabilityFindingsParams is parameters of listTenantDeliverabilityFindings operation.
type ListTenantDeliverabilityFindingsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListTenantIdentityProvidersParams is parameters of listTenantIdentityProviders operation.
type ListTenantIdentityProvidersParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListTenantSuppressionsParams is parameters of listTenantSuppressions operation.
type ListTenantSuppressionsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Case-insensitive literal search across operation-specific resource fields.
	Q OptString `json:",omitempty,omitzero"`
	// Filter by suppression reason.
	Reason OptSuppressionReason `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// ListWebhookEndpointDeliveriesParams is parameters of listWebhookEndpointDeliveries operation.
type ListWebhookEndpointDeliveriesParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}

// ListWebhookEndpointsParams is parameters of listWebhookEndpoints operation.
type ListWebhookEndpointsParams struct {
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// PutListenerMTARateLimitOverrideParams is parameters of putListenerMTARateLimitOverride operation.
type PutListenerMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// PutTenantMTARateLimitOverrideParams is parameters of putTenantMTARateLimitOverride operation.
type PutTenantMTARateLimitOverrideParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// ReorderRoutingRuleParams is parameters of reorderRoutingRule operation.
type ReorderRoutingRuleParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	RuleID     uuid.UUID
}

// ReplaceDomainParams is parameters of replaceDomain operation.
type ReplaceDomainParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Tenant domain identifier.
	DomainID uuid.UUID
}

// ReplaceRoutingRuleParams is parameters of replaceRoutingRule operation.
type ReplaceRoutingRuleParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	RuleID     uuid.UUID
}

// ReplaceSendingDomainPolicyParams is parameters of replaceSendingDomainPolicy operation.
type ReplaceSendingDomainPolicyParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// RotateWebhookEndpointSecretParams is parameters of rotateWebhookEndpointSecret operation.
type RotateWebhookEndpointSecretParams struct {
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}

// SearchTenantResourcesParams is parameters of searchTenantResources operation.
type SearchTenantResourcesParams struct {
	Q     string
	Types []TenantSearchResourceType `json:",omitempty"`
	// Maximum number of resources to return.
	PageSize OptInt `json:",omitempty,omitzero"`
	// Opaque continuation token returned by the previous page.
	PageToken OptString `json:",omitempty,omitzero"`
	// Tenant slug.
	Slug TenantSlug
}

// SendSMTPForwardDestinationVerificationParams is parameters of sendSMTPForwardDestinationVerification operation.
type SendSMTPForwardDestinationVerificationParams struct {
	// Tenant slug.
	Slug TenantSlug
	// SMTP forward destination identifier.
	DestinationID uuid.UUID
}

// SetAutoReplyTemplateActiveParams is parameters of setAutoReplyTemplateActive operation.
type SetAutoReplyTemplateActiveParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Auto-reply template identifier.
	TemplateID uuid.UUID
}

// SetRoutingRuleActiveParams is parameters of setRoutingRuleActive operation.
type SetRoutingRuleActiveParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
	RuleID     uuid.UUID
}

// SetSMTPRelayActiveParams is parameters of setSMTPRelayActive operation.
type SetSMTPRelayActiveParams struct {
	// Tenant slug.
	Slug    TenantSlug
	RelayID uuid.UUID
}

// SetStorageIntegrationActiveParams is parameters of setStorageIntegrationActive operation.
type SetStorageIntegrationActiveParams struct {
	// Tenant slug.
	Slug          TenantSlug
	IntegrationID uuid.UUID
}

// SetTenantIdentityProviderAutoGrantParams is parameters of setTenantIdentityProviderAutoGrant operation.
type SetTenantIdentityProviderAutoGrantParams struct {
	// Tenant slug.
	Slug  TenantSlug
	IdpID uuid.UUID
}

// SetWebhookEndpointActiveParams is parameters of setWebhookEndpointActive operation.
type SetWebhookEndpointActiveParams struct {
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}

// UpdateAutoReplyTemplateParams is parameters of updateAutoReplyTemplate operation.
type UpdateAutoReplyTemplateParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Auto-reply template identifier.
	TemplateID uuid.UUID
}

// UpdateInboundRouteParams is parameters of updateInboundRoute operation.
type UpdateInboundRouteParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Inbound route identifier.
	RouteID uuid.UUID
}

// UpdateListenerParams is parameters of updateListener operation.
type UpdateListenerParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// UpdateListenerDefaultTerminalActionParams is parameters of updateListenerDefaultTerminalAction operation.
type UpdateListenerDefaultTerminalActionParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// UpdateListenerRspamdScanningParams is parameters of updateListenerRspamdScanning operation.
type UpdateListenerRspamdScanningParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Listener identifier.
	ListenerID uuid.UUID
}

// UpdateRecipientSetParams is parameters of updateRecipientSet operation.
type UpdateRecipientSetParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Immutable tenant-scoped recipient-set reference.
	SetRef string
}

// UpdateSMTPRelayParams is parameters of updateSMTPRelay operation.
type UpdateSMTPRelayParams struct {
	// Tenant slug.
	Slug    TenantSlug
	RelayID uuid.UUID
}

// UpdateStorageIntegrationParams is parameters of updateStorageIntegration operation.
type UpdateStorageIntegrationParams struct {
	// Tenant slug.
	Slug          TenantSlug
	IntegrationID uuid.UUID
}

// UpdateTenantIdentityProvisioningParams is parameters of updateTenantIdentityProvisioning operation.
type UpdateTenantIdentityProvisioningParams struct {
	// Tenant slug.
	Slug TenantSlug
}

// UpdateTenantSuppressionParams is parameters of updateTenantSuppression operation.
type UpdateTenantSuppressionParams struct {
	// Tenant slug.
	Slug TenantSlug
	// Plain mailbox address without a display name.
	EmailAddress string
}

// UpdateWebhookEndpointParams is parameters of updateWebhookEndpoint operation.
type UpdateWebhookEndpointParams struct {
	// Tenant slug.
	Slug       TenantSlug
	EndpointID uuid.UUID
}
