// Code generated by ogen, DO NOT EDIT.
package api

type AddRecipientSetMemberRes interface {
	addRecipientSetMemberRes()
}

type BatchAddRecipientSetMembersRes interface {
	batchAddRecipientSetMembersRes()
}

type BatchDeleteRecipientSetMembersRes interface {
	batchDeleteRecipientSetMembersRes()
}

type ClaimTenantIdentityAccessRes interface {
	claimTenantIdentityAccessRes()
}

type CreateAPIKeyRes interface {
	createAPIKeyRes()
}

type CreateAutoReplyTemplateRes interface {
	createAutoReplyTemplateRes()
}

type CreateDomainRes interface {
	createDomainRes()
}

type CreateInboundRouteRes interface {
	createInboundRouteRes()
}

type CreateListenerRes interface {
	createListenerRes()
}

type CreateRecipientSetRes interface {
	createRecipientSetRes()
}

type CreateRoutingRuleRes interface {
	createRoutingRuleRes()
}

type CreateSMTPForwardDestinationRes interface {
	createSMTPForwardDestinationRes()
}

type CreateSMTPRelayRes interface {
	createSMTPRelayRes()
}

type CreateStorageIntegrationRes interface {
	createStorageIntegrationRes()
}

type CreateTenantAppleIdentityProviderRes interface {
	createTenantAppleIdentityProviderRes()
}

type CreateTenantAzureADIdentityProviderRes interface {
	createTenantAzureADIdentityProviderRes()
}

type CreateTenantGitHubEnterpriseServerIdentityProviderRes interface {
	createTenantGitHubEnterpriseServerIdentityProviderRes()
}

type CreateTenantGitHubIdentityProviderRes interface {
	createTenantGitHubIdentityProviderRes()
}

type CreateTenantGitLabIdentityProviderRes interface {
	createTenantGitLabIdentityProviderRes()
}

type CreateTenantGitLabSelfHostedIdentityProviderRes interface {
	createTenantGitLabSelfHostedIdentityProviderRes()
}

type CreateTenantGoogleIdentityProviderRes interface {
	createTenantGoogleIdentityProviderRes()
}

type CreateTenantIdentityProviderRes interface {
	createTenantIdentityProviderRes()
}

type CreateTenantJWTIdentityProviderRes interface {
	createTenantJWTIdentityProviderRes()
}

type CreateTenantLDAPIdentityProviderRes interface {
	createTenantLDAPIdentityProviderRes()
}

type CreateTenantOAuthIdentityProviderRes interface {
	createTenantOAuthIdentityProviderRes()
}

type CreateTenantSAMLIdentityProviderRes interface {
	createTenantSAMLIdentityProviderRes()
}

type CreateTenantSuppressionRes interface {
	createTenantSuppressionRes()
}

type CreateWebhookEndpointRes interface {
	createWebhookEndpointRes()
}

type DeleteAPIKeyRes interface {
	deleteAPIKeyRes()
}

type DeleteAutoReplyTemplateRes interface {
	deleteAutoReplyTemplateRes()
}

type DeleteDomainRes interface {
	deleteDomainRes()
}

type DeleteInboundRouteRes interface {
	deleteInboundRouteRes()
}

type DeleteListenerMTARateLimitOverrideRes interface {
	deleteListenerMTARateLimitOverrideRes()
}

type DeleteListenerRes interface {
	deleteListenerRes()
}

type DeleteRecipientSetMemberRes interface {
	deleteRecipientSetMemberRes()
}

type DeleteRecipientSetRes interface {
	deleteRecipientSetRes()
}

type DeleteRoutingRuleRes interface {
	deleteRoutingRuleRes()
}

type DeleteSMTPForwardDestinationRes interface {
	deleteSMTPForwardDestinationRes()
}

type DeleteSMTPRelayRes interface {
	deleteSMTPRelayRes()
}

type DeleteStorageIntegrationRes interface {
	deleteStorageIntegrationRes()
}

type DeleteTenantIdentityProviderRes interface {
	deleteTenantIdentityProviderRes()
}

type DeleteTenantMTARateLimitOverrideRes interface {
	deleteTenantMTARateLimitOverrideRes()
}

type DeleteTenantSuppressionRes interface {
	deleteTenantSuppressionRes()
}

type DeleteWebhookEndpointRes interface {
	deleteWebhookEndpointRes()
}

type GetAutoReplyTemplateByRefRes interface {
	getAutoReplyTemplateByRefRes()
}

type GetAutoReplyTemplateRes interface {
	getAutoReplyTemplateRes()
}

type GetDomainRes interface {
	getDomainRes()
}

type GetInboundRouteRes interface {
	getInboundRouteRes()
}

type GetListenerMTARateLimitOverrideRes interface {
	getListenerMTARateLimitOverrideRes()
}

type GetListenerRes interface {
	getListenerRes()
}

type GetMailAnalyticsActivityHeatmapRes interface {
	getMailAnalyticsActivityHeatmapRes()
}

type GetMailAnalyticsBreakdownRes interface {
	getMailAnalyticsBreakdownRes()
}

type GetMailAnalyticsComparisonRes interface {
	getMailAnalyticsComparisonRes()
}

type GetMailAnalyticsDomainLifecycleRes interface {
	getMailAnalyticsDomainLifecycleRes()
}

type GetMailAnalyticsLifecycleRes interface {
	getMailAnalyticsLifecycleRes()
}

type GetMailAnalyticsOverviewRes interface {
	getMailAnalyticsOverviewRes()
}

type GetMailAnalyticsSeriesRes interface {
	getMailAnalyticsSeriesRes()
}

type GetMailAnalyticsTaskSizeStatisticsRes interface {
	getMailAnalyticsTaskSizeStatisticsRes()
}

type GetRecipientSetRes interface {
	getRecipientSetRes()
}

type GetRoutingRuleRes interface {
	getRoutingRuleRes()
}

type GetSMTPForwardDestinationByRefRes interface {
	getSMTPForwardDestinationByRefRes()
}

type GetSMTPForwardDestinationRes interface {
	getSMTPForwardDestinationRes()
}

type GetSMTPRelayByRefRes interface {
	getSMTPRelayByRefRes()
}

type GetSMTPRelayRes interface {
	getSMTPRelayRes()
}

type GetSendingDomainPolicyRes interface {
	getSendingDomainPolicyRes()
}

type GetStorageIntegrationByRefRes interface {
	getStorageIntegrationByRefRes()
}

type GetStorageIntegrationRes interface {
	getStorageIntegrationRes()
}

type GetTenantIdentityProviderRes interface {
	getTenantIdentityProviderRes()
}

type GetTenantIdentityProvisioningRes interface {
	getTenantIdentityProvisioningRes()
}

type GetTenantMTARateLimitOverrideRes interface {
	getTenantMTARateLimitOverrideRes()
}

type GetTenantOutboundPauseRes interface {
	getTenantOutboundPauseRes()
}

type GetTenantQuotasRes interface {
	getTenantQuotasRes()
}

type GetTenantReputationRes interface {
	getTenantReputationRes()
}

type GetTenantRes interface {
	getTenantRes()
}

type GetTenantSuppressionRes interface {
	getTenantSuppressionRes()
}

type GetWebhookEndpointByRefRes interface {
	getWebhookEndpointByRefRes()
}

type GetWebhookEndpointRes interface {
	getWebhookEndpointRes()
}

type ListAPIKeysRes interface {
	listAPIKeysRes()
}

type ListAuditLogRes interface {
	listAuditLogRes()
}

type ListAutoReplyTemplatesRes interface {
	listAutoReplyTemplatesRes()
}

type ListDomainListenerGrantsRes interface {
	listDomainListenerGrantsRes()
}

type ListDomainsRes interface {
	listDomainsRes()
}

type ListInboundRoutesRes interface {
	listInboundRoutesRes()
}

type ListInboundRoutingOutcomesRes interface {
	listInboundRoutingOutcomesRes()
}

type ListListenersRes interface {
	listListenersRes()
}

type ListRecipientSetMembersRes interface {
	listRecipientSetMembersRes()
}

type ListRecipientSetsRes interface {
	listRecipientSetsRes()
}

type ListRoutingRulesRes interface {
	listRoutingRulesRes()
}

type ListSMTPForwardDestinationsRes interface {
	listSMTPForwardDestinationsRes()
}

type ListSMTPRelaysRes interface {
	listSMTPRelaysRes()
}

type ListStorageIntegrationsRes interface {
	listStorageIntegrationsRes()
}

type ListTenantDedicatedIPPoolsRes interface {
	listTenantDedicatedIPPoolsRes()
}

type ListTenantDeliverabilityFindingsRes interface {
	listTenantDeliverabilityFindingsRes()
}

type ListTenantIdentityProvidersRes interface {
	listTenantIdentityProvidersRes()
}

type ListTenantSuppressionsRes interface {
	listTenantSuppressionsRes()
}

type ListWebhookEndpointDeliveriesRes interface {
	listWebhookEndpointDeliveriesRes()
}

type ListWebhookEndpointsRes interface {
	listWebhookEndpointsRes()
}

type PutListenerMTARateLimitOverrideRes interface {
	putListenerMTARateLimitOverrideRes()
}

type PutTenantMTARateLimitOverrideRes interface {
	putTenantMTARateLimitOverrideRes()
}

type ReorderRoutingRuleRes interface {
	reorderRoutingRuleRes()
}

type ReplaceDomainRes interface {
	replaceDomainRes()
}

type ReplaceRoutingRuleRes interface {
	replaceRoutingRuleRes()
}

type ReplaceSendingDomainPolicyRes interface {
	replaceSendingDomainPolicyRes()
}

type RotateWebhookEndpointSecretRes interface {
	rotateWebhookEndpointSecretRes()
}

type SearchTenantResourcesRes interface {
	searchTenantResourcesRes()
}

type SendSMTPForwardDestinationVerificationRes interface {
	sendSMTPForwardDestinationVerificationRes()
}

type SetAutoReplyTemplateActiveRes interface {
	setAutoReplyTemplateActiveRes()
}

type SetRoutingRuleActiveRes interface {
	setRoutingRuleActiveRes()
}

type SetSMTPRelayActiveRes interface {
	setSMTPRelayActiveRes()
}

type SetStorageIntegrationActiveRes interface {
	setStorageIntegrationActiveRes()
}

type SetTenantIdentityProviderAutoGrantRes interface {
	setTenantIdentityProviderAutoGrantRes()
}

type SetWebhookEndpointActiveRes interface {
	setWebhookEndpointActiveRes()
}

type UpdateAutoReplyTemplateRes interface {
	updateAutoReplyTemplateRes()
}

type UpdateInboundRouteRes interface {
	updateInboundRouteRes()
}

type UpdateListenerDefaultTerminalActionRes interface {
	updateListenerDefaultTerminalActionRes()
}

type UpdateListenerRes interface {
	updateListenerRes()
}

type UpdateListenerRspamdScanningRes interface {
	updateListenerRspamdScanningRes()
}

type UpdateRecipientSetRes interface {
	updateRecipientSetRes()
}

type UpdateSMTPRelayRes interface {
	updateSMTPRelayRes()
}

type UpdateStorageIntegrationRes interface {
	updateStorageIntegrationRes()
}

type UpdateTenantIdentityProvisioningRes interface {
	updateTenantIdentityProvisioningRes()
}

type UpdateTenantSuppressionRes interface {
	updateTenantSuppressionRes()
}

type UpdateWebhookEndpointRes interface {
	updateWebhookEndpointRes()
}
